services:
  ors-app:
    container_name: ors-app
    image: openrouteservice/openrouteservice:v8.0.0
    ports:
      - "8080:8082"
    volumes:
      - ./ors-data:/ors-core/data/pbf:z
      - ./ors-config.yml:/home/ors/config/ors-config.yml:z
      - ./graphs:/home/ors/graphs:z
      - ./elevation_cache:/home/ors/elevation_cache:z
      - ./logs/ors:/var/log/ors:z
    environment:
      REBUILD_GRAPHS: "True"
      XMS: "1g"
      XMX: "1g"
